"use client";

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Play, Square, Loader2, Image as ImageIcon, Sparkles } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import type { Article as NewsArticle } from '@/services/newsService';
import { translate, translateBatch } from '@/utils/translate';
import { speakWithGCloud, stopSpeaking } from '@/utils/tts';
import type { TTSLanguage } from '@/utils/tts';
import { useLanguage } from '@/contexts/language-context';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";

interface NewsArticleCardProps {
  article: NewsArticle;
}

// Map categories to emojis as shown in design
const getCategoryDetails = (category: string) => {
  const c = category.toLowerCase();
  if (c.includes('cricket') || c.includes('sport')) return { emoji: '🏏', text: 'Cricket' };
  if (c.includes('kino') || c.includes('film') || c.includes('entertainment')) return { emoji: '🎬', text: 'Kino' };
  if (c.includes('trend') || c.includes('insta')) return { emoji: '💪', text: 'Insta-Trend' };
  if (c.includes('politik') || c.includes('politics')) return { emoji: '🗳️', text: 'Politik' };
  if (c.includes('recht') || c.includes('law')) return { emoji: '⚖️', text: 'Recht' };
  if (c.includes('skillcase')) return { emoji: '🚀', text: 'Skillcase' };
  if (c.includes('india') || c.includes('indien')) return { emoji: '🇮🇳', text: 'Indien' };
  return { emoji: '📰', text: category || 'News' };
};

export default function NewsArticleCard({ article }: NewsArticleCardProps) {
  const { language } = useLanguage();
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [imageError, setImageError] = useState(false);

  // Clean up the summary: remove incomplete API trailing text, and limit to exactly 2 complete sentences.
  const getCleanSummary = (text: string) => {
    if (!text) return '';
    // Remove " [+1234 chars]" or trailing ellipses generated by News APIs
    let cleaned = text.replace(/\[\+\d+ chars\]$/, '').replace(/\.\.\.$/, '').trim();
    // Split by full stops, exclamation marks, or question marks followed by a space
    const sentences = cleaned.match(/[^.!?]+[.!?]+/g);
    if (sentences && sentences.length > 0) {
      // Return 2 complete sentences (or 3 if they are very short)
      return sentences.slice(0, 2).join(' ').trim();
    }
    // Fallback if no punctuation is found, just append a full stop
    return cleaned.endsWith('.') ? cleaned : cleaned + '.';
  };

  const baseSummary = getCleanSummary(article.summary);

  const [displayTitle, setDisplayTitle] = useState(article.title);
  const [displaySummary, setDisplaySummary] = useState(baseSummary);
  const [isTranslating, setIsTranslating] = useState(true);

  // Vocab analysis state
  const [showVocab, setShowVocab] = useState(false);
  const [isAnalysing, setIsAnalysing] = useState(false);
  const [vocabList, setVocabList] = useState<{ de: string; en: string }[] | null>(null);

  useEffect(() => {
    let cancelled = false;
    setIsTranslating(true);
    
    Promise.all([
      translate(article.title, language),
      translate(baseSummary, language),
    ]).then(([t, s]) => {
      if (!cancelled) {
        setDisplayTitle(t);
        setDisplaySummary(s);
        setIsTranslating(false);
      }
    }).catch(() => {
      if (!cancelled) {
         setDisplayTitle(article.title);
         setDisplaySummary(baseSummary);
         setIsTranslating(false);
      }
    });
    
    return () => { cancelled = true; };
  }, [article.title, baseSummary, language]);

  // ── TTS ───────────────────────────────────────────────────────────────────
  const handleTTS = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (isSpeaking) {
      stopSpeaking();
      setIsSpeaking(false);
      return;
    }
    const text = displaySummary;
    const lang: TTSLanguage = language === 'de' ? 'de' : 'en';
    speakWithGCloud(
      text,
      lang,
      () => setIsSpeaking(true),
      () => setIsSpeaking(false),
    );
  };

  const handleAnalyse = async (e: React.MouseEvent) => {
    e.stopPropagation();
    setShowVocab(true);
    if (!vocabList && !isAnalysing) {
      setIsAnalysing(true);
      try {
        // Extract 4-5 nice long words from the text (simulating key vocab extraction)
        const cleanText = displaySummary.replace(/[^\wäöüÄÖÜß]+/g, ' ').trim();
        const words = Array.from(new Set(cleanText.split(' ').filter(w => w.length >= 6)))
          .sort((a,b) => b.length - a.length)
          .slice(0, 5);
          
        if (words.length > 0) {
          // Translate the words individually from current language (e.g. 'de') to opposite (e.g. 'en')
          const target = language === 'de' ? 'en' : 'de';
          const translated = await translateBatch(words, target, language);
          
          setVocabList(words.map((w, i) => ({ 
            de: language === 'de' ? w : translated[i], 
            en: language === 'en' ? w : translated[i] 
          })));
        } else {
          setVocabList([]);
        }
      } catch (err) {
        console.error("Vocab analysis failed", err);
        setVocabList([]);
      }
      setIsAnalysing(false);
    }
  };

  const { emoji, text: catText } = getCategoryDetails(article.category || article.source || 'News');
  
  // Randomly assign 'EINFACH' or 'SEHR EINFACH' for the demo like the screenshots
  const difficulty = Math.random() > 0.8 ? 'SEHR EINFACH' : 'EINFACH';

  return (
    <>
      <Card
        className="bg-card border-card shadow-lg text-card-foreground overflow-hidden flex flex-col h-full hover:border-gray-600 transition-all rounded-2xl"
      >
        {/* Image Container with Badges over it */}
        <div className="relative w-full h-48 bg-gray-800 overflow-hidden rounded-t-2xl">
          {!imageError && article.imageUrl ? (
            <img
              src={article.imageUrl}
              alt={displayTitle}
              className="w-full h-full object-cover"
              onError={() => setImageError(true)}
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center bg-gray-800/50">
              <ImageIcon size={48} className="text-gray-500" />
            </div>
          )}
          
          {/* Badges Overlay */}
          <div className="absolute top-3 left-3 flex gap-2">
            <span className="bg-primary text-black text-xs font-bold px-3 py-1 rounded-full flex items-center gap-1 shadow-md">
              <span>{emoji}</span> {catText}
            </span>
            <span className="bg-black/70 backdrop-blur-sm text-white text-xs font-bold px-3 py-1 rounded-full border border-white/10 shadow-md">
              {difficulty}
            </span>
          </div>
        </div>

        {/* Content */}
        <div className="p-5 flex flex-col h-full bg-card rounded-b-2xl">
          {/* Title */}
          <CardHeader className="p-0 mb-3">
            <CardTitle className="text-xl font-bold leading-tight line-clamp-2 text-white flex items-start gap-2">
              {isTranslating && <Loader2 size={16} className="animate-spin mt-1 shrink-0 text-gray-400" />}
              {displayTitle}
            </CardTitle>
          </CardHeader>

          {/* Summary */}
          <CardContent className="p-0 mb-4 flex-grow">
            <CardDescription className="text-[15px] leading-relaxed text-gray-400">
              {displaySummary}
            </CardDescription>
          </CardContent>

          {/* Footer (Source and Buttons) */}
          <CardFooter className="p-0 flex justify-between items-center mt-auto">
            {/* Source left side */}
            <span className="text-sm text-gray-500 italic">
              {article.source || 'News'}
            </span>

            {/* Action buttons right side */}
            <div className="flex gap-3 items-center">
              {/* Play TTS Button */}
              <button
                onClick={handleTTS}
                disabled={isTranslating}
                title={isSpeaking ? 'Stop TTS' : 'Play TTS'}
                className="bg-primary hover:bg-yellow-400 text-black rounded-full p-2.5 transition-colors disabled:opacity-50"
              >
                {isSpeaking ? <Square size={16} className="fill-black" /> : <Play size={16} className="fill-black ml-0.5" />}
              </button>

              {/* Analyse Button */}
              <Button
                size="sm"
                variant="default"
                className="bg-secondary hover:bg-cyan-400 text-black font-bold rounded-xl px-4 flex items-center gap-1.5 shadow-md border-none"
                onClick={handleAnalyse}
                disabled={isTranslating}
              >
                <Sparkles size={16} /> Analyse
              </Button>
            </div>
          </CardFooter>
        </div>
      </Card>

      {/* Vocabulary Analysis Modal */}
      <Dialog open={showVocab} onOpenChange={setShowVocab}>
        <DialogContent className="bg-card text-white border-gray-700 sm:max-w-[425px] dialog-content">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-xl font-bold">
              <Sparkles className="text-secondary" /> Vocabulary Analysis
            </DialogTitle>
            <DialogDescription className="text-gray-400">
              Key {language === 'de' ? 'German' : 'English'} words from this article translated to {language === 'de' ? 'English' : 'German'}.
            </DialogDescription>
          </DialogHeader>

          <div className="mt-4 space-y-3">
            {isAnalysing ? (
              <div className="flex justify-center p-8">
                <Loader2 className="animate-spin text-gray-400 w-8 h-8" />
              </div>
            ) : vocabList && vocabList.length > 0 ? (
              vocabList.map((item, i) => (
                <div key={i} className="flex justify-between items-center p-3 rounded-xl bg-gray-800/80 border border-gray-700/50">
                  <span className="font-bold text-lg text-primary">{item.de}</span>
                  <span className="text-gray-300 capitalize">{item.en}</span>
                </div>
              ))
            ) : (
              <div className="text-center text-gray-500 py-6 text-sm">
                No key vocabulary could be extracted from this article.
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
